/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as YeniKonuRouteImport } from './routes/yeni-konu'
import { Route as YeniMesajlarRouteImport } from './routes/yeni-mesajlar'
import { Route as KategoriCategoryIdRouteImport } from './routes/kategori.$categoryId'
import { Route as KonuThreadIdRouteImport } from './routes/konu.$threadId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const YeniKonuRoute = YeniKonuRouteImport.update({
  id: '/yeni-konu',
  path: '/yeni-konu',
  getParentRoute: () => rootRouteImport,
} as any)
const YeniMesajlarRoute = YeniMesajlarRouteImport.update({
  id: '/yeni-mesajlar',
  path: '/yeni-mesajlar',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriCategoryIdRoute = KategoriCategoryIdRouteImport.update({
  id: '/kategori/$categoryId',
  path: '/kategori/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const KonuThreadIdRoute = KonuThreadIdRouteImport.update({
  id: '/konu/$threadId',
  path: '/konu/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/yeni-konu': typeof YeniKonuRoute
  '/yeni-mesajlar': typeof YeniMesajlarRoute
  '/kategori/$categoryId': typeof KategoriCategoryIdRoute
  '/konu/$threadId': typeof KonuThreadIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/yeni-konu': typeof YeniKonuRoute
  '/yeni-mesajlar': typeof YeniMesajlarRoute
  '/kategori/$categoryId': typeof KategoriCategoryIdRoute
  '/konu/$threadId': typeof KonuThreadIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/yeni-konu': typeof YeniKonuRoute
  '/yeni-mesajlar': typeof YeniMesajlarRoute
  '/kategori/$categoryId': typeof KategoriCategoryIdRoute
  '/konu/$threadId': typeof KonuThreadIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/yeni-konu'
    | '/yeni-mesajlar'
    | '/kategori/$categoryId'
    | '/konu/$threadId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/yeni-konu'
    | '/yeni-mesajlar'
    | '/kategori/$categoryId'
    | '/konu/$threadId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/yeni-konu'
    | '/yeni-mesajlar'
    | '/kategori/$categoryId'
    | '/konu/$threadId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  YeniKonuRoute: typeof YeniKonuRoute
  YeniMesajlarRoute: typeof YeniMesajlarRoute
  KategoriCategoryIdRoute: typeof KategoriCategoryIdRoute
  KonuThreadIdRoute: typeof KonuThreadIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yeni-konu': {
      id: '/yeni-konu'
      path: '/yeni-konu'
      fullPath: '/yeni-konu'
      preLoaderRoute: typeof YeniKonuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yeni-mesajlar': {
      id: '/yeni-mesajlar'
      path: '/yeni-mesajlar'
      fullPath: '/yeni-mesajlar'
      preLoaderRoute: typeof YeniMesajlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$categoryId': {
      id: '/kategori/$categoryId'
      path: '/kategori/$categoryId'
      fullPath: '/kategori/$categoryId'
      preLoaderRoute: typeof KategoriCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konu/$threadId': {
      id: '/konu/$threadId'
      path: '/konu/$threadId'
      fullPath: '/konu/$threadId'
      preLoaderRoute: typeof KonuThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  YeniKonuRoute: YeniKonuRoute,
  YeniMesajlarRoute: YeniMesajlarRoute,
  KategoriCategoryIdRoute: KategoriCategoryIdRoute,
  KonuThreadIdRoute: KonuThreadIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
