/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GizlilikRouteImport } from './routes/gizlilik'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as LoginRouteImport } from './routes/login'
import { Route as YasalUyariRouteImport } from './routes/yasal-uyari'
import { Route as YeniKonuRouteImport } from './routes/yeni-konu'
import { Route as YeniMesajlarRouteImport } from './routes/yeni-mesajlar'
import { Route as IkinciElIndexRouteImport } from './routes/ikinci-el/index'
import { Route as IkinciElListingIdRouteImport } from './routes/ikinci-el/$listingId'
import { Route as IkinciElYeniRouteImport } from './routes/ikinci-el/yeni'
import { Route as IsIlaniIndexRouteImport } from './routes/is-ilani/index'
import { Route as IsIlaniJobIdRouteImport } from './routes/is-ilani/$jobId'
import { Route as IsIlaniYeniRouteImport } from './routes/is-ilani/yeni'
import { Route as KategoriCategoryIdRouteImport } from './routes/kategori.$categoryId'
import { Route as KonuThreadIdRouteImport } from './routes/konu.$threadId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikRoute = GizlilikRouteImport.update({
  id: '/gizlilik',
  path: '/gizlilik',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const YasalUyariRoute = YasalUyariRouteImport.update({
  id: '/yasal-uyari',
  path: '/yasal-uyari',
  getParentRoute: () => rootRouteImport,
} as any)
const YeniKonuRoute = YeniKonuRouteImport.update({
  id: '/yeni-konu',
  path: '/yeni-konu',
  getParentRoute: () => rootRouteImport,
} as any)
const YeniMesajlarRoute = YeniMesajlarRouteImport.update({
  id: '/yeni-mesajlar',
  path: '/yeni-mesajlar',
  getParentRoute: () => rootRouteImport,
} as any)
const IkinciElIndexRoute = IkinciElIndexRouteImport.update({
  id: '/ikinci-el/',
  path: '/ikinci-el/',
  getParentRoute: () => rootRouteImport,
} as any)
const IkinciElListingIdRoute = IkinciElListingIdRouteImport.update({
  id: '/ikinci-el/$listingId',
  path: '/ikinci-el/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const IkinciElYeniRoute = IkinciElYeniRouteImport.update({
  id: '/ikinci-el/yeni',
  path: '/ikinci-el/yeni',
  getParentRoute: () => rootRouteImport,
} as any)
const IsIlaniIndexRoute = IsIlaniIndexRouteImport.update({
  id: '/is-ilani/',
  path: '/is-ilani/',
  getParentRoute: () => rootRouteImport,
} as any)
const IsIlaniJobIdRoute = IsIlaniJobIdRouteImport.update({
  id: '/is-ilani/$jobId',
  path: '/is-ilani/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const IsIlaniYeniRoute = IsIlaniYeniRouteImport.update({
  id: '/is-ilani/yeni',
  path: '/is-ilani/yeni',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriCategoryIdRoute = KategoriCategoryIdRouteImport.update({
  id: '/kategori/$categoryId',
  path: '/kategori/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const KonuThreadIdRoute = KonuThreadIdRouteImport.update({
  id: '/konu/$threadId',
  path: '/konu/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gizlilik': typeof GizlilikRoute
  '/kvkk': typeof KvkkRoute
  '/login': typeof LoginRoute
  '/yasal-uyari': typeof YasalUyariRoute
  '/yeni-konu': typeof YeniKonuRoute
  '/yeni-mesajlar': typeof YeniMesajlarRoute
  '/ikinci-el/$listingId': typeof IkinciElListingIdRoute
  '/ikinci-el/yeni': typeof IkinciElYeniRoute
  '/is-ilani/$jobId': typeof IsIlaniJobIdRoute
  '/is-ilani/yeni': typeof IsIlaniYeniRoute
  '/kategori/$categoryId': typeof KategoriCategoryIdRoute
  '/konu/$threadId': typeof KonuThreadIdRoute
  '/ikinci-el/': typeof IkinciElIndexRoute
  '/is-ilani/': typeof IsIlaniIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gizlilik': typeof GizlilikRoute
  '/kvkk': typeof KvkkRoute
  '/login': typeof LoginRoute
  '/yasal-uyari': typeof YasalUyariRoute
  '/yeni-konu': typeof YeniKonuRoute
  '/yeni-mesajlar': typeof YeniMesajlarRoute
  '/ikinci-el/$listingId': typeof IkinciElListingIdRoute
  '/ikinci-el/yeni': typeof IkinciElYeniRoute
  '/is-ilani/$jobId': typeof IsIlaniJobIdRoute
  '/is-ilani/yeni': typeof IsIlaniYeniRoute
  '/kategori/$categoryId': typeof KategoriCategoryIdRoute
  '/konu/$threadId': typeof KonuThreadIdRoute
  '/ikinci-el': typeof IkinciElIndexRoute
  '/is-ilani': typeof IsIlaniIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gizlilik': typeof GizlilikRoute
  '/kvkk': typeof KvkkRoute
  '/login': typeof LoginRoute
  '/yasal-uyari': typeof YasalUyariRoute
  '/yeni-konu': typeof YeniKonuRoute
  '/yeni-mesajlar': typeof YeniMesajlarRoute
  '/ikinci-el/$listingId': typeof IkinciElListingIdRoute
  '/ikinci-el/yeni': typeof IkinciElYeniRoute
  '/is-ilani/$jobId': typeof IsIlaniJobIdRoute
  '/is-ilani/yeni': typeof IsIlaniYeniRoute
  '/kategori/$categoryId': typeof KategoriCategoryIdRoute
  '/konu/$threadId': typeof KonuThreadIdRoute
  '/ikinci-el/': typeof IkinciElIndexRoute
  '/is-ilani/': typeof IsIlaniIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gizlilik'
    | '/kvkk'
    | '/login'
    | '/yasal-uyari'
    | '/yeni-konu'
    | '/yeni-mesajlar'
    | '/ikinci-el/$listingId'
    | '/ikinci-el/yeni'
    | '/is-ilani/$jobId'
    | '/is-ilani/yeni'
    | '/kategori/$categoryId'
    | '/konu/$threadId'
    | '/ikinci-el/'
    | '/is-ilani/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gizlilik'
    | '/kvkk'
    | '/login'
    | '/yasal-uyari'
    | '/yeni-konu'
    | '/yeni-mesajlar'
    | '/ikinci-el/$listingId'
    | '/ikinci-el/yeni'
    | '/is-ilani/$jobId'
    | '/is-ilani/yeni'
    | '/kategori/$categoryId'
    | '/konu/$threadId'
    | '/ikinci-el'
    | '/is-ilani'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/gizlilik'
    | '/kvkk'
    | '/login'
    | '/yasal-uyari'
    | '/yeni-konu'
    | '/yeni-mesajlar'
    | '/ikinci-el/$listingId'
    | '/ikinci-el/yeni'
    | '/is-ilani/$jobId'
    | '/is-ilani/yeni'
    | '/kategori/$categoryId'
    | '/konu/$threadId'
    | '/ikinci-el/'
    | '/is-ilani/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GizlilikRoute: typeof GizlilikRoute
  KvkkRoute: typeof KvkkRoute
  LoginRoute: typeof LoginRoute
  YasalUyariRoute: typeof YasalUyariRoute
  YeniKonuRoute: typeof YeniKonuRoute
  YeniMesajlarRoute: typeof YeniMesajlarRoute
  IkinciElListingIdRoute: typeof IkinciElListingIdRoute
  IkinciElYeniRoute: typeof IkinciElYeniRoute
  IsIlaniJobIdRoute: typeof IsIlaniJobIdRoute
  IsIlaniYeniRoute: typeof IsIlaniYeniRoute
  KategoriCategoryIdRoute: typeof KategoriCategoryIdRoute
  KonuThreadIdRoute: typeof KonuThreadIdRoute
  IkinciElIndexRoute: typeof IkinciElIndexRoute
  IsIlaniIndexRoute: typeof IsIlaniIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik': {
      id: '/gizlilik'
      path: '/gizlilik'
      fullPath: '/gizlilik'
      preLoaderRoute: typeof GizlilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yasal-uyari': {
      id: '/yasal-uyari'
      path: '/yasal-uyari'
      fullPath: '/yasal-uyari'
      preLoaderRoute: typeof YasalUyariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yeni-konu': {
      id: '/yeni-konu'
      path: '/yeni-konu'
      fullPath: '/yeni-konu'
      preLoaderRoute: typeof YeniKonuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yeni-mesajlar': {
      id: '/yeni-mesajlar'
      path: '/yeni-mesajlar'
      fullPath: '/yeni-mesajlar'
      preLoaderRoute: typeof YeniMesajlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ikinci-el/': {
      id: '/ikinci-el/'
      path: '/ikinci-el'
      fullPath: '/ikinci-el/'
      preLoaderRoute: typeof IkinciElIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ikinci-el/$listingId': {
      id: '/ikinci-el/$listingId'
      path: '/ikinci-el/$listingId'
      fullPath: '/ikinci-el/$listingId'
      preLoaderRoute: typeof IkinciElListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ikinci-el/yeni': {
      id: '/ikinci-el/yeni'
      path: '/ikinci-el/yeni'
      fullPath: '/ikinci-el/yeni'
      preLoaderRoute: typeof IkinciElYeniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/is-ilani/': {
      id: '/is-ilani/'
      path: '/is-ilani'
      fullPath: '/is-ilani/'
      preLoaderRoute: typeof IsIlaniIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/is-ilani/$jobId': {
      id: '/is-ilani/$jobId'
      path: '/is-ilani/$jobId'
      fullPath: '/is-ilani/$jobId'
      preLoaderRoute: typeof IsIlaniJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/is-ilani/yeni': {
      id: '/is-ilani/yeni'
      path: '/is-ilani/yeni'
      fullPath: '/is-ilani/yeni'
      preLoaderRoute: typeof IsIlaniYeniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$categoryId': {
      id: '/kategori/$categoryId'
      path: '/kategori/$categoryId'
      fullPath: '/kategori/$categoryId'
      preLoaderRoute: typeof KategoriCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konu/$threadId': {
      id: '/konu/$threadId'
      path: '/konu/$threadId'
      fullPath: '/konu/$threadId'
      preLoaderRoute: typeof KonuThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GizlilikRoute: GizlilikRoute,
  KvkkRoute: KvkkRoute,
  LoginRoute: LoginRoute,
  YasalUyariRoute: YasalUyariRoute,
  YeniKonuRoute: YeniKonuRoute,
  YeniMesajlarRoute: YeniMesajlarRoute,
  IkinciElListingIdRoute: IkinciElListingIdRoute,
  IkinciElYeniRoute: IkinciElYeniRoute,
  IsIlaniJobIdRoute: IsIlaniJobIdRoute,
  IsIlaniYeniRoute: IsIlaniYeniRoute,
  KategoriCategoryIdRoute: KategoriCategoryIdRoute,
  KonuThreadIdRoute: KonuThreadIdRoute,
  IkinciElIndexRoute: IkinciElIndexRoute,
  IsIlaniIndexRoute: IsIlaniIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
